site_name: Bespoken Docs
site_description: Bespoken Documentation
repo_url: https://github.com/bespoken/bst
site_dir: 'site'
strict: true
google_analytics: ['UA-99287066-2', 'docs.bespoken.io']

pages:
- Home: index.md
- Getting Started: getting_started.md
- Alexa Skill Configuration: alexa_skills_kit_configuration.md
- Commands:
    - bst deploy: commands/deploy.md
    - bst intend: commands/intend.md
    - bst proxy: commands/proxy.md
    - bst speak: commands/speak.md
    - bst launch: commands/launch.md
- API Reference: api_nav.md
- Tutorials - Alexa Skills:
    - Node.js Lambda: tutorials/tutorial_lambda_nodejs.md
    - Local Java Server: tutorials/tutorial_local_server_java.md
    - Python & Flask-Ask: tutorials/tutorial_flask_ask_python.md
    - Alexa Emulator & Node.js: tutorials/tutorial_bst_emulator_nodejs.md
- Tutorials - Google Actions:
    - With Cloud Functions: tutorials/tutorial_cloud_function.md
    - With API.AI: tutorials/tutorial_configuring_api_ai.md
- Tutorials - AWS Lambdas:
    - Running Lambdas Locally: tutorials/tutorial_lambda_local.md
    - Debugging Lambdas Locally: tutorials/tutorial_lambda_debugger.md
    - Deploying Lambdas: tutorials/tutorial_lambda_deploy.md

theme: readthedocs

markdown_extensions:

extra_css: [assets/css/style.css]

extra_javascript:
  - api/assets/js/main.js
  - api/assets/js/search.js